services:
  adminer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    networks:
      - localdev

networks:
  localdev:
    name: localdev_net
    driver: bridge
    external: true
